language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
before_install:
  - export DJANGO_SETTINGS_MODULE=django_themes.test_settings
install:
  - pip install tox
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - coverage run --branch --source=dbtemplates `which django-admin.py` test django_themes
  - coverage report --omit="django_themes/test*,django_themes/migrations*"
