# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='The order of themes for resolution of static and template files, higher ranked themes will override ')),
                ('is_active', models.BooleanField(default=False, help_text='')),
                ('author', models.CharField(help_text='', max_length=256, verbose_name='author')),
                ('name', models.CharField(help_text='The name of this theme', max_length=256, verbose_name='name')),
                ('version', models.CharField(help_text='', max_length=256, verbose_name='version')),
                ('path', models.CharField(help_text='', max_length=256, verbose_name='path')),
                ('description', models.TextField(blank=True, help_text='A brief description of the files in this theme.', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
